export const HeaderStaticLinks = {
  movies_categories: {
    genre: [],
    country: [
      {
        id: 1,
        nameRu: 'Русские',
        nameEn: 'Russian',
        link: '/movies/all?countries=rs',
      },
      {
        id: 2,
        nameRu: 'Американские',
        nameEn: 'American',
        link: '/movies/all?countries=us',
      },
      {
        id: 3,
        nameRu: 'Советские',
        nameEn: 'Soviet',
        link: '/movies/all?countries=su',
      },
    ],
    year: [
      {
        id: 1,
        year: '2023',
        link: '/movies/all?year=2023',
      },
      {
        id: 2,
        year: '2022',
        link: '/movies/all?year=2022',
      },
      {
        id: 3,
        year: '2021',
        link: '/movies/all?year=2021',
      },
      {
        id: 4,
        year: '2020',
        link: '/movies/all?year=2020',
      },
    ],
    selection: [
      {
        id: 1,
        nameRu: 'Новинки',
        nameEn: 'New',
        link: 'https://www.ivi.ru/new/movie-new',
      },
      {
        id: 2,
        nameRu: 'Подборки',
        nameEn: 'Collections',
        link: 'https://www.ivi.ru/collections',
      },
      {
        id: 3,
        nameRu: 'Иви.Рейтинг',
        nameEn: 'IVI.Rating',
        link: 'https://www.ivi.ru/movies/all?ivi_rating_10_gte=7&sort=ivi&rating_part=main&rating_model=ready',
      },
      {
        id: 4,
        nameRu: 'Трейлеры',
        nameEn: 'Trailers',
        link: 'https://www.ivi.ru/trailers',
      },
      {
        id: 5,
        nameRu: 'Что посмотреть',
        nameEn: 'Some good shit',
        link: 'https://www.ivi.ru/goodmovies',
      },
      {
        id: 6,
        nameRu: 'Фильмы в HD',
        nameEn: 'HD movies',
        link: 'https://www.ivi.ru/collections/movies-hd',
      },
      {
        id: 7,
        nameRu: 'Выбор ИВИ',
        nameEn: 'IVI Choice',
        link: 'https://www.ivi.ru/collections/vyibor-ivi',
      },
      {
        id: 8,
        nameRu: 'Новинки подписки',
        nameEn: 'New in subscription',
        link: 'https://www.ivi.ru/collections/very-new-svod?sort=priority_in_collection',
      },
    ],
  },
  series_categories: {
    genre: [
      {
        id: 1,
        nameRu: 'Биография',
        nameEn: 'Biography',
        link: 'https://www.ivi.ru/series/biography',
      },
      {
        id: 2,
        nameRu: 'Боевики',
        nameEn: 'Militants',
        link: 'https://www.ivi.ru/series/boeviki',
      },
      {
        id: 3,
        nameRu: 'Военные',
        nameEn: 'War',
        link: 'https://www.ivi.ru/series/voennye',
      },
      {
        id: 4,
        nameRu: 'Детективы',
        nameEn: 'Detective',
        link: 'https://www.ivi.ru/series/detective',
      },
      {
        id: 5,
        nameRu: 'Для всей семьи',
        nameEn: 'Family',
        link: 'https://www.ivi.ru/series/dlya_vsej_semi',
      },
      {
        id: 6,
        nameRu: 'Дорамы',
        nameEn: 'Dorama',
        link: 'https://www.ivi.ru/series/doramy',
      },
      {
        id: 7,
        nameRu: 'Драмы',
        nameEn: 'Drama',
        link: 'https://www.ivi.ru/series/dramy',
      },
      {
        id: 8,
        nameRu: 'Исторические',
        nameEn: 'Historical',
        link: 'https://www.ivi.ru/series/history',
      },
      {
        id: 9,
        nameRu: 'Комедийные',
        nameEn: 'Comedy',
        link: 'https://www.ivi.ru/series/comedy',
      },
      {
        id: 10,
        nameRu: 'Криминальные',
        nameEn: 'Crime',
        link: 'https://www.ivi.ru/series/crime',
      },
      {
        id: 11,
        nameRu: 'Медицинские',
        nameEn: 'Medicine',
        link: 'https://www.ivi.ru/series/medicine',
      },
      {
        id: 12,
        nameRu: 'Мелодрамы',
        nameEn: 'melodramas',
        link: 'https://www.ivi.ru/series/melodramyi',
      },
      {
        id: 13,
        nameRu: 'Мистические',
        nameEn: 'Mystic',
        link: 'https://www.ivi.ru/series/misticheskie',
      },
      {
        id: 14,
        nameRu: 'Приключения',
        nameEn: 'Adventures',
        link: 'https://www.ivi.ru/series/adventures',
      },
      {
        id: 15,
        nameRu: 'Романтические',
        nameEn: 'Romance',
        link: 'https://www.ivi.ru/series/romanticheskie',
      },
      {
        id: 16,
        nameRu: 'Телешоу',
        nameEn: 'TVShow',
        link: 'https://www.ivi.ru/series/tvshow',
      },
      {
        id: 17,
        nameRu: 'Триллеры',
        nameEn: 'Thriller',
        link: 'https://www.ivi.ru/series/thriller',
      },
      {
        id: 18,
        nameRu: 'Турецкие',
        nameEn: 'Turkish',
        link: 'https://www.ivi.ru/series/turetskie',
      },
      {
        id: 19,
        nameRu: 'Документальные',
        nameEn: 'Documentary',
        link: 'https://www.ivi.ru/series/documentary',
      },
      {
        id: 20,
        nameRu: 'Ужасы',
        nameEn: 'Horror',
        link: 'https://www.ivi.ru/series/horror',
      },
      {
        id: 21,
        nameRu: 'Фантастические',
        nameEn: 'Fantastic',
        link: 'https://www.ivi.ru/series/scifi',
      },
      {
        id: 22,
        nameRu: 'Фэнтези',
        nameEn: 'Fantasy',
        link: 'https://www.ivi.ru/series/fantasy',
      },
    ],
    country: [
      {
        id: 1,
        nameRu: 'Русские',
        nameEn: 'Russian',
        link: 'https://www.ivi.ru/series/ru',
      },
      {
        id: 2,
        nameRu: 'Зарубежные',
        nameEn: 'Foreign',
        link: 'https://www.ivi.ru/series/foreign',
      },
      {
        id: 3,
        nameRu: 'Американские',
        nameEn: 'US',
        link: 'https://www.ivi.ru/series/us',
      },
      {
        id: 5,
        nameRu: 'Корейские',
        nameEn: 'Korean',
        link: 'https://www.ivi.ru/series/kr',
      },
      {
        id: 6,
        nameRu: 'Турецкие',
        nameEn: 'Turkish',
        link: 'https://www.ivi.ru/series/tr',
      },
    ],
    year: [
      {
        id: 1,
        year: '2023',
        link: 'https://www.ivi.ru/series/2023',
      },
      {
        id: 2,
        year: '2022',
        link: 'https://www.ivi.ru/series/2022',
      },
      {
        id: 3,
        year: '2021',
        link: 'https://www.ivi.ru/series/2021',
      },
      {
        id: 4,
        year: '2020',
        link: 'https://www.ivi.ru/series/2020',
      },
    ],
    selection: [
      {
        id: 1,
        nameRu: 'Новинки',
        nameEn: 'New',
        link: 'https://www.ivi.ru/new/series-new',
      },
      {
        id: 2,
        nameRu: 'Иви.Рейтинг',
        nameEn: 'IVI.Rating',
        link: 'https://www.ivi.ru/series/all?ivi_rating_10_gte=7&sort=ivi&rating_part=main&rating_model=ready',
      },
      {
        id: 3,
        nameRu: 'Сериалы в HD',
        nameEn: 'HD Series',
        link: 'https://www.ivi.ru/collections/series-hd',
      },
      {
        id: 4,
        nameRu: 'Бесплатные сериалы',
        nameEn: 'Free series',
        link: 'https://www.ivi.ru/collections/tvshow-free?sort=new',
      },
    ],
  },
  animation_categories: {
    genre: [
      {
        id: 1,
        nameRu: 'Аниме',
        nameEn: 'Anime',
        link: 'https://www.ivi.ru/animation/anime',
      },
      {
        id: 2,
        nameRu: 'Боевик',
        nameEn: 'Militants',
        link: 'https://www.ivi.ru/animation/boeviki',
      },
      {
        id: 3,
        nameRu: 'Детектив',
        nameEn: 'Detectives',
        link: 'https://www.ivi.ru/animation/detectives',
      },
      {
        id: 4,
        nameRu: 'Для взрослых',
        nameEn: 'Adult',
        link: 'https://www.ivi.ru/animation/vzroslye',
      },
      {
        id: 5,
        nameRu: 'Для всей семьи',
        nameEn: 'Family',
        link: 'https://www.ivi.ru/animation/dlya_vsej_semi',
      },
      {
        id: 6,
        nameRu: 'Для детей',
        nameEn: 'Kids',
        link: 'https://www.ivi.ru/animation/detskiy',
      },
      {
        id: 7,
        nameRu: 'Драма',
        nameEn: 'Drama',
        link: 'https://www.ivi.ru/animation/drama',
      },
      {
        id: 8,
        nameRu: 'История',
        nameEn: 'Historical',
        link: 'https://www.ivi.ru/animation/istoricheskie',
      },
      {
        id: 9,
        nameRu: 'Комедия',
        nameEn: 'Comedy',
        link: 'https://www.ivi.ru/animation/comedy',
      },
      {
        id: 10,
        nameRu: 'Криминальные',
        nameEn: 'Crime',
        link: 'https://www.ivi.ru/animation/crime',
      },
      {
        id: 11,
        nameRu: 'Мюзикл',
        nameEn: 'Musical',
        link: 'https://www.ivi.ru/animation/musical',
      },
      {
        id: 12,
        nameRu: 'Полнометражные',
        nameEn: 'Movies',
        link: 'https://www.ivi.ru/animation/polnometrazhnye',
      },
      {
        id: 13,
        nameRu: 'Приключения',
        nameEn: 'Adventure',
        link: 'https://www.ivi.ru/animation/adventure',
      },
      {
        id: 14,
        nameRu: 'Развивающие',
        nameEn: 'Educational',
        link: 'https://www.ivi.ru/animation/razvivayuschie',
      },
      {
        id: 15,
        nameRu: 'Сериалы',
        nameEn: 'Series',
        link: 'https://www.ivi.ru/animation/serialy',
      },
      {
        id: 16,
        nameRu: 'Спорт',
        nameEn: 'Sport',
        link: 'https://www.ivi.ru/animation/sport',
      },
      {
        id: 17,
        nameRu: 'Триллер',
        nameEn: 'Thriller',
        link: 'https://www.ivi.ru/animation/thriller',
      },
      {
        id: 18,
        nameRu: 'Ужасы',
        nameEn: 'Horror',
        link: 'https://www.ivi.ru/animation/horror',
      },
      {
        id: 19,
        nameRu: 'Фантастика',
        nameEn: 'Fantasic',
        link: 'https://www.ivi.ru/animation/fantastika',
      },
      {
        id: 20,
        nameRu: 'Фэнтези',
        nameEn: 'Fantasy',
        link: 'https://www.ivi.ru/animation/fentezi',
      },
    ],
    country: [
      {
        id: 1,
        nameRu: 'Советские',
        nameEn: 'Soviet',
        link: 'https://www.ivi.ru/animation/su',
      },
      {
        id: 2,
        nameRu: 'Русские',
        nameEn: 'Russian',
        link: 'https://www.ivi.ru/animation/ru',
      },
      {
        id: 3,
        nameRu: 'Американские',
        nameEn: 'US',
        link: 'https://www.ivi.ru/animation/us',
      },
      {
        id: 4,
        nameRu: 'Зарубежные',
        nameEn: 'Foreign',
        link: 'https://www.ivi.ru/animation/foreign',
      },
    ],
    year: [
      {
        id: 1,
        year: '2023',
        link: 'https://www.ivi.ru/series/2023',
      },
      {
        id: 2,
        year: '2022',
        link: 'https://www.ivi.ru/series/2022',
      },
      {
        id: 3,
        year: '2021',
        link: 'https://www.ivi.ru/series/2021',
      },
      {
        id: 4,
        year: '2020',
        link: 'https://www.ivi.ru/series/2020',
      },
    ],
    selection: [
      {
        id: 1,
        nameRu: 'Новинки',
        nameEn: 'New',
        link: 'https://www.ivi.ru/new/animation-new',
      },
      {
        id: 2,
        nameRu: 'Мультики в HD',
        nameEn: 'HD cartoons',
        link: 'https://www.ivi.ru/collections/cartoons-hd',
      },
    ],
  },
};
